# Generated by Django 2.0.6 on 2018-06-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preps', '0002_auto_20180627_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
