# Generated by Django 2.0.6 on 2018-06-28 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preps', '0003_stage_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='actions',
            new_name='stages',
        ),
    ]
