# Generated by Django 2.0.6 on 2018-07-06 09:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('preps', '0009_auto_20180706_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 7, 6, 9, 1, 45, 26659, tzinfo=utc), null=True),
        ),
    ]
