# Generated by Django 2.0.6 on 2018-06-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
