# Generated by Django 2.0.6 on 2018-07-02 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preps', '0006_auto_20180628_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='name',
        ),
    ]
