# Generated by Django 2.0.6 on 2018-07-02 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preps', '0007_remove_stage_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='actions',
        ),
        migrations.AddField(
            model_name='stage',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='preps.Action'),
        ),
    ]
