# Generated by Django 2.0.6 on 2018-07-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preps', '0008_auto_20180702_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
