# Generated by Django 2.0.6 on 2018-07-06 13:15

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('preps', '0010_auto_20180706_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='stages',
        ),
        migrations.AddField(
            model_name='stage',
            name='sample',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='preps.Sample'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stage',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 7, 6, 13, 15, 10, 216298, tzinfo=utc), null=True),
        ),
    ]
