# Generated by Django 2.0.6 on 2018-07-19 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preps', '0012_auto_20180706_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgressoProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_to_date', models.CharField(max_length=15)),
                ('this_month', models.CharField(max_length=15)),
                ('accrep_text', models.CharField(max_length=255)),
                ('fund_type', models.CharField(max_length=25)),
                ('funding', models.CharField(max_length=25)),
                ('project_text', models.CharField(max_length=25)),
                ('project', models.CharField(max_length=25)),
                ('balance_of_grant_avail', models.CharField(max_length=15)),
                ('ltd_budget', models.CharField(max_length=15)),
                ('ltd_actual', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'AGR55.CELLGEN_CORE_PROJECTS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WarehouseSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('supplier_name', models.CharField(max_length=255)),
                ('donor_id', models.CharField(max_length=255)),
                ('cohort', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=20)),
                ('public_name', models.CharField(max_length=255)),
                ('common_name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('phenotype', models.CharField(max_length=255)),
                ('cost_code', models.CharField(max_length=20)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='stage',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='preps.Owner'),
        ),
    ]
