# Generated by Django 2.0.6 on 2018-07-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preps', '0013_auto_20180719_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('cost_code', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('balance_avail', models.FloatField()),
                ('is_core', models.BooleanField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='agressoproject',
            options={},
        ),
    ]
