# Generated by Django 2.0.6 on 2018-07-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preps', '0014_auto_20180721_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseStudy',
            fields=[
                ('id_study_lims', models.IntegerField(primary_key=True, serialize=False)),
                ('study_title', models.TextField()),
                ('faculty_sponsor', models.TextField()),
                ('ethically_approved', models.TextField()),
                ('accession_number', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='agressoproject',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['cost_code']},
        ),
    ]
